### ISSUE TITLE
Checklist for go-live

### ISSUE THREAD

**Issue by guw** [EclipseFdn/planeteclipse.org#4]
This is a checklist of items we need to do when this is going live.

- [ ] Make old Git read-only
- [x] Disable Gerrit
- [x] Merge latest blog/feed updates (eg., https://git.eclipse.org/r/140369)
- [x] Update wiki page
- [x] Ensure all committers have commit rights

**Comment by guw** [comment]
@chrisguindon Please add items you need as well.

**Comment by chrisguindon** [comment]
Thanks for the list @guw! I did not know you could create checklist in a github issue!

I believe that all committers have commit access. The current list is:

1. @caniszczyk 
2. @eclipsewebmaster 
3. @chrisguindon 
4. @guw 

There is also 2 open invitations for:

1. @irbull 
2. @jmini 

Am I missing anyone else?

**Comment by jmini** [comment]
"open invitation" - what does it mean?

--- 

On the planet page when clicking on the "+ Add your blog" link, following message box is displayed:

> *Add your blog*
> 
> If you would like your blog added to the feed, please have a look at our [guidelines](http://wiki.eclipse.org/index.php/PlanetEclipse#Guidelines) and then open a [request](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=PlanetEclipse.org) in the Eclipse Bugzilla with your feed specific information.

I think the "request" link should now point to:
https://github.com/EclipseFdn/planeteclipse.org/issues/new?template=add_blog.md

**Comment by chrisguindon** [comment]
> "open invitation" - what does it mean?

The invitations are pending. I am waiting for you and @irbull to accept my invitation to the planeteclipse.org github team.

> I think the "request" link should now point to:
https://github.com/EclipseFdn/planeteclipse.org/issues/new?template=add_blog.md

I agree. This would be consistent with what we are doing with jakartablogs.ee. 

How about:

Want to become a PlanetEclipse author? To add your blog to the feed, please have a look at our [guidelines](https://github.com/EclipseFdn/planeteclipse.org#guidelines) and then open a [GitHub issue](https://github.com/EclipseFdn/planeteclipse.org/issues/new?template=add_blog.md) or create a pull request with your feed-specific information.

**Comment by jmini** [comment]
As there is no notification on GitHub (I probably got a mail, but I am not really reading them), it was hard to find.
Now that I know that it is for a team, I found it while visiting the organization page: https://github.com/orgs/EclipseFdn/invitation

Thank you.

Ok with the new text.

**Comment by chrisguindon** [comment]
I created PR to include the missing commits:
https://github.com/EclipseFdn/planeteclipse.org/pull/6

The history of both repos (github and gerrit) are different now. 

I created new commits for these 3 changes since the location of planet.ini has changed with this new repo.

**Comment by eclipsewebmaster** [comment]
@guw, after talking to @chrisguindon , I think the best option for steps 1&2 is to simply remove the existing repo at Eclipse.org .  Leaving it anywhere other than Github is likely to confuse people, so let's make everyones life easier.

**Comment by mbarbero** [comment]
We're live, should we close this one?

**Comment by chrisguindon** [comment]
@mbarbero we still need to update the wiki and retire the repo from eclipse.org.

**Comment by chrisguindon** [comment]
I made some update the the wiki page:
https://wiki.eclipse.org/Planet_Eclipse

**Comment by chrisguindon** [comment]
@eclipsewebmaster Please move forward as this is the last item on our list!

**Comment by chrisguindon** [comment]
I created an archive branch to store a copy of the last version of the git repo on www.eclipse.org:

https://github.com/EclipseFdn/planeteclipse.org/tree/archive

**Comment by eclipsewebmaster** [comment]
Done.

**Comment by chrisguindon** [comment]
Thanks!

Closing this bug!
